# Generated by Django 4.2.5 on 2023-11-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Band',
            new_name='Band1',
        ),
    ]
